# This is a condensed version of [release-yml].
#
# [release-yml]: https://github.com/paskausks/rust-bin-github-workflows/blob/894a4f2debade42f8d7b5b95f493eaa33fdeb81b/.github/workflows/release.yml
on: push

name: Build and test

jobs:
  build:
    runs-on: ubuntu-latest

    name: Ubuntu, Rust stable
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust (rustup)
      run: |
        rustup update stable --no-self-update
        rustup default stable
        rustup component add rustfmt
        rustup component add clippy
        rustc --version
      shell: bash

    # See https://github.com/diwic/dbus-rs/tree/350ca9bfa88e6e1964d3a0d4a128d63a885eb3f7#requirements
    - name: Install dependencies
      run: sudo apt-get install libdbus-1-dev

    - name: Build (release)
      run: cargo build --verbose --release

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Run clippy
      run: cargo clippy -- -D clippy::all

    - name: Test
      run: cargo test
